# Generated by Django 4.2.3 on 2023-07-18 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0002_movie_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="dislikes_cnt",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="movie",
            name="likes_cnt",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Reaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("LIKE", "LIKE"), ("DISLIKE", "DISLIKE")],
                        max_length=15,
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="movie.movie",
                    ),
                ),
            ],
        ),
    ]
