# Generated by Django 4.2.3 on 2023-07-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0004_remove_movie_dislikes_cnt_remove_movie_likes_cnt"),
    ]

    operations = [
        migrations.AddField(
            model_name="reaction",
            name="reactions_cnt",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
