# Generated by Django 4.2.3 on 2023-07-19 00:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0005_reaction_reactions_cnt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reaction",
            name="reactions_cnt",
        ),
    ]
