# Generated by Django 4.2.1 on 2023-07-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0006_remove_reaction_reactions_cnt"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="num",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="Reaction",
        ),
    ]
