# Generated by Django 4.2.1 on 2023-07-19 05:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0007_movie_num_delete_reaction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="num",
            new_name="views",
        ),
    ]
